# conda env create --file environment.yml
name: augmented-dev
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.11
- pip==24.0
- pandas==2.2.0
- jupyterlab==4.1.5
- pip:
  - arxiv==2.1.0
  - beautifulsoup4==4.12.*
  - cachetools==5.3.3
  - chromadb==0.4.24
  - crewai==0.22.5
  - datasets==2.18.0
  - faiss-cpu==1.8.0
  - fastapi==0.110.0
  - google-api-core==2.17.1
  - google-auth==2.28.2
  - google-cloud-aiplatform==1.44.0
  - google-cloud-core==2.4.1
  - google-cloud-resource-manager==1.12.3
  - google-cloud-storage==2.15.0
  - huggingface-hub==0.21.4
  - ipywidgets==8.1.2
  - jinja2==3.1.3
  - jupyter-ai==2.12.0
  - langchain==0.1.12
  - langchain-google-vertexai==0.1.1
  - langchain-openai==0.0.5
  - langchain_decorators==0.5.4
  - langsmith==0.1.26
  - llama-index==0.10.10
  - llama-index-core==0.10.12
  - llama-index-embeddings-openai==0.1.6
  - llama-index-llms-openai==0.1.6
  - llama-index-vector-stores-chroma==0.1.4
  - markdown==3.5.2
  - nltk==3.8.1
  - openai==1.14.0
  - promptwatch==0.4.4
  - pydantic==2.6.4
  - pypdf==4.1.0
  - python-dotenv==1.0.0
  - pyyaml==6.0.1
  - replicate==0.24.0
  - requests==2.31.0
  - streamlit==1.32.2
  - tiktoken==0.5.2
  - tqdm==4.66.2
  - unstructured==0.12.6
  - wikipedia==1.4.0
  - wolframalpha==5.0.0